### PR TITLE
Additional documentation annotations

### PR DESCRIPTION
**Pull request by eyesniper2**
Target Minecraft versions: Any
Requirements: None
Related issues: N/A

Description:
Added in @DocumentationID and  @RequiredPlugins annotations to help addon authors better document their code base using Skript built in annotations.

### CODE REVIEW

**Comment by Snow-Pyon** [comment]
Looks good overall, I have two questions though:

* Are we gonna need implement these in the current Skript syntaxes or are you gonna do it in another PR?
* Would you modify the current documentation to adapt this change? If not, I'll be doing it anyways.

**Comment by eyesniper2** [comment]
I added the DocumentationID into the EvtPeriodical class since I have been having issues specifically with that class in producing an unique keys because of the way it is [initialized](https://github.com/eyesniper2/Skript/blob/e4d66aaa992606160c621651a5e5b385b769b47b/src/main/java/ch/njol/skript/events/EvtPeriodical.java#L43) with different descriptions and examples. 

However for adding in the RequiredPlugins I was unsure of all the places within Skript that this would cover. These changes were mainly made to help addons that use third party plugins better document them. I also did not add Required Plugins to the Skript Documentation generator since I was unsure if Skript even needed it.

**Comment by Snow-Pyon** [comment]
Well, pretty much everything within the hooks package may need it but that isn't an issue. I'll merge it and add the required information if @bensku doesn't have any complains on this one, I was gonna edit examples of every syntax on the documentation after all.

**Comment by bensku** [comment]
The HTML generator embedded with Skript will need to support at least setting the id of a syntax element. It is of course possible to do this after merge, if @Snow-Pyon has time or someone else can PR it.

**Comment by Snow-Pyon** [comment]
@bensku Alright, I'll do it tomorrow then.

@eyesniper2 thanks for the contribution!

**Comment by bensku** [comment]
I had some other requests for changes, too...

**Pull request merged**
