### PR TITLE
Updated aliases and fixed scripts

### PR DESCRIPTION
**Pull request by Weefle**
Target Minecraft versions: 1.12.1
Requirements: No requirement
Related issues: No related issue

Description:
I just updated the aliases (english) to the latest (2.0.8) and fixed the scripts problem who caused errors on load (equip anything.sk, item command.sk, drop fixes.sk) to work with the new aliases

### CODE REVIEW

**Comment by bensku** [comment]
Breaking changes in aliases? Just... Why?

**Comment by Weefle** [comment]
The aliases was already broken

**Comment by bensku** [comment]
Ah, I see. Should have checked that before I guess.

**Comment by Weefle** [comment]
It must be said to tim740 that there are problems with the glasses in aliases

**Pull request merged**
