### PR TITLE
Add expression support to permission message

### PR DESCRIPTION
**Pull request by Pikachu920**
Target Minecraft versions: Any
Requirements: None
Related issues: #652
Description:
Now you can use expressions in perm messages:
```
command /test:
  permission: asd
  permission message: {var} is %{var}%, %player%
  trigger:
    broadcast "you did it!"
```

### CODE REVIEW

**Comment by JRoy** [comment]
Thank fucking christ this is a thing now.

**Comment by TheLimeGlass** [comment]
Does this also apply to the cooldown message of commands or was that already present?

**Comment by Pikachu920** [comment]
cooldown messages do already have support

**Comment by bensku** [comment]
Github seems to have trouble providing merge options for this PR. See #1199 for details.

**Pull request merged**
