### PR TITLE
Scope API (not finished)

### PR DESCRIPTION
**Pull request by Syst3ms**
The Scope API allows for easy creating of scopes/sections/"pseudo-conditions". It's not done at all, don't merge.

### CODE REVIEW

**Comment by TheBentoBox** [comment]
I have a vague idea, but what exactly does this do? Is this just to standardize the code behind sections such as conditions, events, loops, and functions?

**Comment by TheLimeGlass** [comment]
@TheBentoBox Basically it's a system similar to MundoSk's custom Scope.

In Tlat's Scope system 

Scope is what Tlat calls his system. Syst3ms is stealing the name.

Basically Tlat can utilize custom conditions and read data inside the condition.

So like how he does
```
Async:
    #All code in this trigger will be ran Async
```
That kind of stuff, if that makes sense. This is an attempt to make it easier for developers to utilize that system. Because Tlat uses alot of reflection to access and do this, since this stuff was never ment to be accessed in Skript (Njol made it that way)

It's basically like rewriting the whole parser in order to do it. I personally think it's not needed as you can use reflection like Tlat. As doing this changes everything.

**Comment by Syst3ms** [comment]
No I'm not rewriting the whole parser. Only a part of ScriptLoader. That's still quite important, but not too much. This doesn't change everything because I've rewritten all classes that extend TriggerSection (I think). Conditions, effects, expressions and even events aren't affected (I think).

**Comment by Syst3ms** [comment]
**I am closing this pull request as my previous commits are here, which I don't want. I'll get the code fully remade before pull-requesting again. I will be also waiting for my empty function arguments PR to be merged before PR-ing again.**

**Comment by bensku** [comment]
I would prefer to throw current API to rubbish bin. It is undocumented, messy, and relies too much on nullness annotations - which no addon devs use as far as I know.

If reworking something breaks addons, so be it. I'm confident that the benefits in future will be greater.

**Pull request closed without merging**
