### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Legoman99573**
We already would know about it if the other PR is accepted. Just updated the README.md to label before people open an issue about it.

### CODE REVIEW

**Comment by Blueyescat** [comment]
Doesn't Skript support Spigot fully? what is **`spigot should work as well, but isnt recommended`**

**Comment by Legoman99573** [comment]
Yeah, ill fix that, but should have gotten in other commit, but wound up making a seperate patch. Ill update that.

**Comment by Pikachu920** [comment]
there's a typo. preformance should be performance

**Comment by bensku** [comment]
Closed with the other nonfunctional PR.

**Pull request closed without merging**
