### PR TITLE
Comment SkriptParser + Allow empty function arguments + Make list indexes sorted by add order and not alphanumerically

### PR DESCRIPTION
**Pull request by Syst3ms**
About empty function arguments, I do not guarantee this will work at all.

### CODE REVIEW

**Comment by bensku** [comment]
Need to do quick look through the code, but this will be there for next release.

**Comment by Syst3ms** [comment]
These commits remove alphanumeric sorting of list indexes. With this commit, variables are sorted by add order.

**Comment by btk5h** [comment]
1. The database doesn't guarantee that rows will be sent in insertion order. Variable ordering may be inconsistent when the server loads.
2. This is a breaking change for scripts that delete indices and readd them (`delete {test::1}` followed by `set {test::1}`)

I would much rather keep the existing ordering as it is the least surprising behavior.

**Comment by TheBentoBox** [comment]
I think these newer commits that remove alphanumeric sorting should be included, but you should make it require a new config option which is set to false by default due to the issue pointed out by @btk5h. This would be very useful to many people but it can (and probably will) break a lot of old scripts, so it should be something that has to be enabled, so it's only done by people who know what they're doing and want it.

That being said, I'd also recommend not doing things that way (relying on stuff remaining in the same order in the list based on index), as it's not very reliable and there's probably a smarter way to store your data.

**Comment by bensku** [comment]
I agree with @btk5h that sorting for list keys is very, very necessary. The alternative is not having them in the order they were added, but instead in *undefined* order. In other words, you still couldn't trust that they are in the order you added, while they might be so 99% of times. Having a lag spike or disk usage at 100% might break everything.

The previous part of this pull request looks good, though. I can merge this once the latter commits have been removed or at least sorting is back (I saw you did couple of other useful changes, too).

**Comment by Syst3ms** [comment]
Fixed merge conflicts due to new file headers

**Comment by xXAndrew28Xx** [comment]
@Syst3ms More merge conflicts btw.

**Comment by Syst3ms** [comment]
Thanks

**Comment by Syst3ms** [comment]
Actually, I feel like there is not much point to this PR anymore. Closing.

**Pull request closed without merging**
