### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by sgdc3**
- Fix maven compiler and libraries
- Cleanup unused code and remove unused imports
- (WIP) Remove unused annotations (80% done)

### CODE REVIEW

**Comment by sgdc3** [comment]
@bensku

**Comment by bensku** [comment]
IDE project files are necessary for checking nullness annotations correctly. Java compliance specified in Maven file is irrelevant, since Skript uses (and due to nullness annotations, must use) Eclipse Java Compiler. These things are not easy to change

I really would like to hear why you want to do the other changes, though. You'll probably need new PR anyway...

**Comment by sgdc3** [comment]
There are alternatives to the eclipse annotations, maybe we should use one of them.

**Comment by bensku** [comment]
Yeah, there are. IntelliJ annotations for example, but oh well, those are also IDE dependent. If you have ideas, maybe we can do something...

**Pull request closed without merging**
