### PR TITLE
Add information about my private Jenkins with builds of Skript plugin

### PR DESCRIPTION
**Pull request by kacperduras**
Why not?

### CODE REVIEW

**Comment by bensku** [comment]
I already have nightly builds. Mind explaining what advantage this would have, except minor convenience?

**Comment by kacperduras** [comment]
```
What if your server was hacked?
```
This is a small, private CI. Access via only SSH keys, proxy via CF, only 80 and 21 ports is open, nothing more.

```
I already have nightly builds.
```
Why don't you public these builds?

**Comment by TheBentoBox** [comment]
> Why don't you publish these builds?

Nightly builds are posted automatically in [this repository](https://github.com/bensku/skript-build).

**Comment by kacperduras** [comment]
@TheBentoBox Ok, thanks a lot, but where is the redirect to this repo in README?

**Comment by bensku** [comment]
It is not there for a reason. I do not want most people to use the nightly build. As opposed to nightlies in some other projects, Skript's nightlies may or may not be safe to use.

One potential thing to break with nightly Skript releases would be variables. If serialization format of something is changed, old data is of course updated. However, if I decide to revert the change - could totally happen - you cannot use the next release without wiping your variable database. With so called pre-releases this is very unlikely to happen.

Most people should not use or even know of Skript's nightly builds. The ones who should very likely do know already.

**Comment by kacperduras** [comment]
Ok, thanks for your feedback :D

**Pull request closed without merging**
