### PR TITLE
Shutdown the server if they use craftbukkit.

### PR DESCRIPTION
**Pull request by Legoman99573**
Description:
Reference similar to #933, except we disable the whole plugin before it loads to save from loading unnecessarily when the plugin would be disabled. Changed  #Lines 197-565

### CODE REVIEW

**Comment by Legoman99573** [comment]
@bensku i can do that, but i think people will say "Skript is crashing my server. Pls fix. Ill update the readme later saying its commonly known"

**Comment by Legoman99573** [comment]
@bensku updated my commit. Should check within onLoad() which will occur before onEnable()

**Comment by bensku** [comment]
You code does not compile. Hmh, I guess I'll do this myself. *Always* check that your code compiles!

**Comment by Legoman99573** [comment]
sorry bensku, havent had internet at home and is hard to compile in public locations.

**Pull request closed without merging**
