### PR TITLE
Add chat format expression

### PR DESCRIPTION
**Pull request by xXAndrew28Xx**
Related issues: Adds enhancement #548 

Description:
Adds a settable expression for the chat format of an AsyncPlayerChatEvent.

### CODE REVIEW

**Comment by Tuke-Nuke** [comment]
Hey, just a suggestion, don't you think it would be easier if the format is returned "properly for scripters"? Because it defaults to `<%1$s> %2$s` and them every time is necessary to explain that String formatting stuffs. I think it would be cool if it literally returns as `<[PLAYER]> [MESSAGE]` so these tags are simple to explain (or can be anything else but string format). Also it would apply in `change` method aswell, to replace them back to string format.

**Comment by xXAndrew28Xx** [comment]
I was thinking about that, I wasn't sure of the best way to do it. I might do it the way you said as that makes sense.

**Comment by bensku** [comment]
@Tuke-Nuke is correct, it would be better to have something... More human-readable. Perhaps [player] and [message] (please no caps).

**Comment by xXAndrew28Xx** [comment]
I made the changes.

**Comment by bensku** [comment]
Using those scripter-friendly replace patterns causes the following error:
```[15:11:36 ERROR]: #!#! java.lang.IllegalArgumentException: Illegal group reference
[15:11:36 ERROR]: #!#!     at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
[15:11:36 ERROR]: #!#!     at java.util.regex.Matcher.replaceAll(Matcher.java:955)
[15:11:36 ERROR]: #!#!     at java.lang.String.replaceAll(String.java:2223)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.expressions.ExprChatFormat.convertToNormal(ExprChatFormat.java:108)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.expressions.ExprChatFormat.change(ExprChatFormat.java:96)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:66)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:85)
[15:11:36 ERROR]: #!#!     at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1)
[15:11:36 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[15:11:36 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[15:11:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[15:11:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[15:11:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[15:11:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[15:11:36 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)```

**Comment by xXAndrew28Xx** [comment]
The expression has been fixed.

**Comment by Blueyescat** [comment]
Does it support JSON Chat? It should! :)

**Comment by bensku** [comment]
Ummm how would that be possible, @Blueyescat?

**Comment by Blueyescat** [comment]
Oh no, isn't it possible with `chat format`? So we can't do this without cancel-send :slightly_frowning_face::
```vb
on chat:
    set chat format to "<tooltip:hi>[player]: [message]"
```

**Comment by xXAndrew28Xx** [comment]
@Blueyescat It isn't, the chat format apparently only supports a String.

**Pull request merged**
