### PR TITLE
Add tps expression

### PR DESCRIPTION
**Pull request by Pikachu920**
Target Minecraft versions: Any (kinda)
Requirements: A recent version of Paper, the getTPS method relatively recently moved so this will only work on Paper versions released after that move.
Related issues: None

Description:
Adds a TPS expresssion that returns the last 3 tps numbers. If you can think of a way to support older Paper versions without reflection, i'll add it.

### CODE REVIEW

**Comment by Blueyescat** [comment]
There should be 3 different expressions for the last 3 TPS numbers.

**Comment by Pikachu920** [comment]
i disagree and assuming #1160 gets merged at some point, you could just do `3rd element out of tps`

**Comment by Blueyescat** [comment]
Skript expressions should be English and easy to read/understand

**Comment by Pikachu920** [comment]
can you recommend a syntax?

**Comment by Blueyescat** [comment]
```autohotkey
[the] ([current] tps|tps (of|from) [the] last 1[ ]m[inute[s]])
[thr] tps (of|from) [the] last 5[ ]m[inute[s]]
[thr] tps (of|from) [the] last 15[ ]m[inute[s]]
```

**Comment by Pikachu920** [comment]
i like the idea kinda, but there is no actual guarantee that those values are from those times.

**Comment by bensku** [comment]
It is actually mentioned in [Javadoc](https://ci.destroystokyo.com/userContent/apidocs/org/bukkit/Server.html#getTPS--) of the method you use. I think it is safe to assume that Paper-Server is only commonly used implementation of Paper API.

**Comment by Blueyescat** [comment]
@Pikachu920 that doesn't matter actually, but you can make your own TPS calculator 😛

**Pull request merged**
