### PR TITLE
Add hotbar slot expression

### PR DESCRIPTION
**Pull request by Pikachu920**
Target Minecraft versions: Any
Requirements: None
Related issues: #1044

Description:
Lets you get and set a player's current hotbar slot

### CODE REVIEW

**Comment by Snow-Pyon** [comment]
I don't know whether this is a good way to implement it or not, the syntax at least. Since Skript references `slot` as an ItemStack with a slot number attached to it, having it this way could cause confusion.

@bensku thoughts on this?

**Comment by Pikachu920** [comment]
yeah i thought about that too however i decided against it because slot of player's hotbar slot is a bit akward

**Comment by bensku** [comment]
No. I've said multiple times: add a way to get slot, not number. Then add a way to get a number from slot, with an expression that takes a slot.

**Comment by Pikachu920** [comment]
that sounds like a total pain in the ass for scripters. I have never seen someone legitimately want a Slot. Besides, it would look horrible... `slot of player's hotbar slot`??

**Comment by TheBentoBox** [comment]
Maybe the expression could just be `%slot%'s number`? So it'd be `player's hotbar slot's number`. I'm not sure if that's much better but just an idea.

**Comment by Pikachu920** [comment]
and then you need number of %slot% too, which conflicts with the size expression. Point is, I've never seen a user go "oh wow im so glad this thing is a slot". Especially in this case, player's tool already returns the slot form of this.

**Comment by Snow-Pyon** [comment]
Then wouldn't it be possible to do: `slot number of player's tool`? I'd say it's better that way

**Comment by Pikachu920** [comment]
but then you run into an issue with setting it: `set slot of player's tool to 1` you would think this would move the actual item in their hand to the 1st slot, not what slot they have selected

**Comment by TheLimeGlass** [comment]
This is why I held off on adding things like `clicked item` and stuff because the controversial over using Slot or just the straight number is still being decided. I don't like the Slot system either.

I mean this doesn't even work https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprInventorySlot.java#L83

What's the difference between Slot and InventorySlot? Is it really needed?

In my pull request I fixed this back to Slot https://github.com/TheLimeGlass/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprInventorySlot.java#L84-L105

I think the Slot system was added because back in 1.4 there wasn't very good inventory support, so Njol made a Slot system, also we have to keep in mind serialization and Skript incorporation. I say in 1.13 ditch the whole Slot system if we can.

**Comment by bensku** [comment]
Integers are not to be used to represent slots. Not all slots are in inventories and thus, they do not *always* even have ids. This just acquire the slot; next update will have a way for to get index out of it and even compare it with numbers.

Won't be implicitly *converted* to a number, though. That might cause subtle issues later.

**Comment by bensku** [comment]
I will add an expression that gets current hotbar slot as Skript's Slot for next release. This cannot be merged, I'm afraid.

**Comment by bensku** [comment]
Used your syntax, though. Well done with that :+1:

**Pull request closed without merging**
