### PR TITLE
Silverfish should be added to BlockChangeEvent

### PR DESCRIPTION
**Pull request by Sashie**
This has been sitting secretly in skDragon for a long time for a few people that needed it.
It should have an 'enter' and 'exit' instead of just a general one, go ahead and add that.

### CODE REVIEW

**Comment by bensku** [comment]
Need to have support for it going in AND it going out. Otherwise, seems good.

**Comment by Sashie** [comment]
(not sure why it adds every commit i make to this one pull request)

**Comment by xXAndrew28Xx** [comment]
When you make a pull request, you are asking for one branch of your repository to be merged with this one. Make different branches for different pull requests.

**Comment by Sashie** [comment]
gotcha, thx
also @bensku this has been updated btw

**Pull request merged**
