### PR TITLE
Update BukkitEventValues.java

### PR DESCRIPTION
**Pull request by TheLimeGlass**
Added event values for the InventoryOpenEvent and InventoryCloseEvent 

Event values `event-inventory` and `event-player`

### CODE REVIEW

**Comment by TheBentoBox** [comment]
This would be very useful!

**Comment by Ayase-san** [comment]
There isn't a getPlayer method on these events, you have to get it from the viewers of the inventory.

**Comment by TheLimeGlass** [comment]
@Ayase-san Really? RandomSk has done it for years.

**Comment by TheBentoBox** [comment]
Also am seeing getPlayer in the documentation for both of these.

**Comment by TheLimeGlass** [comment]
@TheBentoBox This adds event values to the `on inventory open` and `on inventory close` event. But I can look into adding entity event-value for the on tame event.

**Comment by Tuke-Nuke** [comment]
Do you see perfectly fine that the `getPlayer` method returns `HumanEntity` not `Player`? You need to cast it, that's what I think @Ayase-san meant.

**Comment by Ayase-san** [comment]
No, I just confused the events @Tuke-Nuke :joy:

**Pull request merged**
