### PR TITLE
Update EffVisualEffect.java

### PR DESCRIPTION
**Pull request by TheLimeGlass**
Works on any version

Add the ability to use `at` for proper grammar, this was really annoying to me, so I added it for anyone else to enjoy.

### CODE REVIEW

**Comment by Snow-Pyon** [comment]
You should be able to use at already, it's a literal that returns an unknown direction. As you can see here:
https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/expressions/LitAt.java

If you aren't able to use it then this might be a bug.

**Comment by bensku** [comment]
At is indeed a valid "direction". Could be a parser bug if it doesn't work.

Could someone verify that this does happen when running Skript without addons?

**Comment by TheLimeGlass** [comment]
So then convert this into an issue? It's minor but very annoying.

**Comment by Snow-Pyon** [comment]
File an issue report explaining how to reproduce it and we'll see what's going on.

**Pull request closed without merging**
