### PR TITLE
Fixed list deletion for databases

### PR DESCRIPTION
**Pull request by Sharpjaws**
Fixed variable list deletion for mysql  and possibly other databases. Attempting to delete variable lists from a database would lead to nothing happening. This fixes that.

### CODE REVIEW

**Comment by TheBentoBox** [comment]
Are you sure this isn't only an issue with your setup somehow? I've always been able to delete list variables without issue, and I am still able to do so:

image

**Comment by Sharpjaws** [comment]
@TheBentoBox Ignore what I just said above I just realised that this problem only happens with mysql databases.

**Comment by TheBentoBox** [comment]
Ahhh I see, sounds nice then

**Comment by bensku** [comment]
Seems good this far. Will come with next feature release.

**Comment by RezzedUp** [comment]
This completely breaks list variables. #843

**Comment by bensku** [comment]
@Sharpjaws I have no idea what you were thinking with this PR, but you certainly did not test it. Sadly that was before I introduced code reviewing for pull requests.

Mistakes happen, but you gotta be very careful when making pull requests. I'm around if I break stuff and monitor all issues for a few days after a release... You are probably not going to do that, are you?

**Pull request merged**
