### PR TITLE
Fix #56 - Make Skript buildable via Maven and javac; decouple from Eclipse

### LINKED ISSUE #56: Unable to build/compile from repository
# Summary

I would like to contribute bug fixes and features to this Skript fork. Before I can do so, I need to be able to build Skript as-is from the latest commit. I seem to be unable to do so, as there are numerous compilation errors and the Maven file is confusing. I was unable to find building instructions.

# Environments

* [Command-line Maven 3.2.1](https://gist.github.com/RoyCurtis/aa64495dbab1169a05705c0bd20bbf82) and JDK 1.8u45
  * Attempted to build using `mvn clean package`
  * [Build success, but resulted in numerous repository warnings and a dud jar file with no built classes](http://vanderprot.gamealition.com/img/5e725.png)
  * [Build log](https://gist.github.com/RoyCurtis/c14d4647ee1ac25546df9c7ed871cb86)
* [IntelliJ IDEA 14.1.6 with repository imported as a Maven project](http://vanderprot.gamealition.com/img/2e716.png)
  * Tested with both JDK 1.7u79 and JDK 1.8u45

# Reproduction
This is how I attempted to build Skript from github using IntelliJ IDEA 14

1. [Cloned the repository using](http://vanderprot.gamealition.com/img/2698e.png) `git clone --depth 1 --branch master https://github.com/bensku/Skript.git`
  * _Cloning only a single commit was necessary for me, as otherwise the repository was too big to download_
2. [Imported the pom.xml file as a project in IntelliJ](http://vanderprot.gamealition.com/img/304d5.png)
  * [Import settings used](http://vanderprot.gamealition.com/img/d4ef9.png), with ["build" profile selected](http://vanderprot.gamealition.com/img/166b8.png)
  * [Using JDK8](http://vanderprot.gamealition.com/img/c8379.png)
  * Overwrote the existing IDEA project
3. [Confirmed that the project was successfully imported by checking dependencies and Maven tab](http://vanderprot.gamealition.com/img/63e60.png)
4. Attempted to make the project (CTRL+F9), [resulting in errors](http://vanderprot.gamealition.com/img/477dd.png)

# Issues

## Fixable

* [WorldEdit classes not found](http://vanderprot.gamealition.com/img/4a9c7.png)
  * [Fixed by adding WorldEdit to the POM file](https://gist.github.com/RoyCurtis/0449f7963fd8e4e9535b62f1988ca792)
* [Use of strings in switch not supported in Java 6 language level](http://vanderprot.gamealition.com/img/e0785.png)
  * [Fixed by changing the POM file to use 1.7](https://gist.github.com/RoyCurtis/82fec57d2c9a6e2a4048129279e6d406)
* [Use of base class' private field](http://vanderprot.gamealition.com/img/acc3e.png)
  * [Fixed by making the field `protected` instead](http://vanderprot.gamealition.com/img/a57e4.png)

## Help needed

* `ch\njol\skript\lang\SkriptParser.java L320, C50: Incompatible types: ch.njol.skript.lang.SyntaxElement cannot be converted to ch.njol.skript.lang.Expression<?>` ([screenshot](http://vanderprot.gamealition.com/img/5ebf5.png))
* `ch\njol\skript\variables\Variables.java L86, C114: Incompatible types: ch.njol.skript.classes.ClassInfo<java.lang.Object> cannot be converted to ch.njol.skript.classes.ClassInfo<? extends org.bukkit.configuration.serialization.ConfigurationSerializable>` ([screenshot](http://vanderprot.gamealition.com/img/c3262.png))
* `mvn clean package` doesn't build a usable jar (it doesn't appear to actually compile anything)

# Suggestions

* To make it easier for future contributors, the `.idea`, `.settings` and `Skript.iml` folders/files should be removed. These are IDE dependent and automatically generated. They should not be committed to version control, as the saved settings may conflict with different setups.
* Instead of bundling WorldEdit and WorldGuard jars, [they should be referred to in the POM using sk89q's repository](http://docs.enginehub.org/manual/worldguard/latest/developer/dependency/)

# Notes

* I also had the two compile errors under "Help needed" when attempting to build Skript from njol's original repository, many months ago. So I do not think these errors are introduced by this or Mirreski's fork

### PR DESCRIPTION
**Pull request by RoyCurtis**
This PR makes major changes to the building and debugging workflow of Skript. It is an attempt at fixing #56 and making it easier for others to contribute fixes and features to Skript.

# WARNING

Accepting and merging this pull request, then pulling the new commits, may result in your Eclipse or IntelliJ settings for Skript being deleted. This is because a commit in this PR deletes Eclipse project files that should not have been committed originally.

To avoid this, I must advise:

- Make a backup of `.classpath`, `.idea`, `.settings` and `Skript.iml`
- Alternatively, do `git clone https://github.com/Gamealition/Skript.git -b build-fix Skript-BuildFixTest` to clone this PR into another directory, for testing or setting up a new workspace

# Rationale

## Moving to Maven

Maven is used in virtually all Bukkit plugin projects as a means of describing a project, pulling dependencies and building a JAR. This is done with `pom.xml`, the Maven build file.

Currently, Skript's POM file is of no use. It has compilation intentionally turned off and various dependencies are wrong/missing.

This PR makes many fixes to the POM file and adds commentary to explain what each bit does. This allows any IDE (e.g. Eclipse, IntelliJ, Netbeans) or CI (e.g. Jenkins) to build and debug the project with consistent settings.

## Decoupling from Eclipse

Currently, Skript relies heavily on Eclipse. As commented in the POM file, Eclipse is used for both compiling the code (using its ecj compiler, rather than javac) and building jar files. It is also used for organizing the project (e.g. setting Java compile level, excluded files), but the settings aren't up-to-date in the repository.

This PR fixes this by removing all Eclipse-related project files and making some code changes, so as not to be dependent on compiler quirks supported by Eclipse's ecj compiler. This makes it easier for other contributors to use their own IDEs (e.g. IntelliJ, NetBeans)

# Testing

* Able to import Maven project into Eclipse Mars.2 and build JAR on Windows 10
* Able to import Maven project into IntelliJ 14 and build JAR on Windows 10
* Able to build JAR by Maven command-line on Windows
* [Able to build JAR by Maven command-line on Ubuntu 15.10 server](http://i.imgur.com/Hzcav4i.png)
* No compilation errors on javac on JDK8
* Built JAR runs without exceptions on local Spigot 1.9 and PaperSpigot 1.9 servers

# Notes

I realize that this is a very invasive pull request. It could break everyone's existing Skript workflow and may require contributors to reconfigure their IDEs or learn Maven.

Because of this, [the PR includes a README file with building and debugging instructions](https://github.com/Gamealition/Skript/blob/build-fix/README.md) for Eclipse and IntelliJ. I have tried to be as descriptive as possible, with screenshots and videos.

I would also like to offer my support with this PR; whether it's by explaining how to merge it, or how to set up Maven with Eclipse, or to explain any of the changes made. If this PR is considered, I can be available on IRC or [by email](roy.adrian.curtis@gmail.com) for this support.

I feel these changes are necessary for the future of Skript's development. As has been discussed on #56, the current issues are a high barrier of entry to other contributors.

### CODE REVIEW

**Comment by bensku** [comment]
Awesome that you did this!

However, I'm bit scared to move away from ECJ. Changing compiler *might* have side effects on Skript's performance. Also, I'd like to keep at least Java 7 support (currently Skript is compiled for Java 6, but that is unnecessary), so that I'll need to test before merging. Just testing, testing and testing for me :)

But finally, there is one quite big problem. Skript relies on Eclipse's @NonNull and @NonNullByDefault more heavily than I had guessed before. ECJ settings are set to throw **compiler error** on *possible* null pointer access. Due to that, Skript methods have absolutely no runtime null checks, since it is not possible to pass a value which could be null. When I want to tell Skript that value is certainly not null, I use assertations; if it is null (oops), JVM will throw clear <code>AssertationError/<code> instead of not-so-clear <code>NullPointerException</code>.

I need (or we need) to find a way to support this for other IDEs, or we must stick with Eclipse (or we need to rewrite most of Skript). No code should be written without those checks, either in IDE or in compiler. I have seen an addon whose developer used IDE without @NonNull support; it passed nulls in one method call and I had lots of *fun* trying to debug that. Having these problems with Skript itself... Well, it is already frustrating to debug (only few comments by Njol...).

**Comment by RoyCurtis** [comment]
I hadn't thought about that. I didn't fully understand what the annotations were used for. Sorry!

What I'd like to try then is help find a way to support the NonNull annotations on other IDEs. I agree it would be a problem if code was submitted that caused NPEs; they are indeed frustrating to debug. 

If such a thing is not possible, then yes we should stick to Eclipse. In that case, I will re-do my pull request to do some of the clean up and README instructions, but still rely on ECJ.

How easy would it be to test performance? Are there any special scripts used for this?

Thank you for the prompt response and explaining all of the above; it's helpful and I learnt more stuff :p

**Comment by bensku** [comment]
Performance testing basically involves throwing a build on our production server and watching TPS numbers. Not that hard :) I have timings support in progress, but it is not yet ready.

ECJ can be used from Maven and from IDEA too (and even without any IDE). However, if the IDE accepts something, which doesn't compile, it slows down coding.

**Comment by bensku** [comment]
Quick update: I have not yet found a way to use Eclipse's annotations in IDEA. However, IDEA has its own similar annotations we could use - some kind of code preprocessor could help with that.

IDE settings will likely be needed as part of git repo, since for default Eclipse only creates warning on null access. With Skript it it configured to create errors.

**Comment by RoyCurtis** [comment]
Sorry for never finishing this; had lost the motivation

**Comment by bensku** [comment]
No worries :) I got rid of Maven, but Eclipse is ptobably here to stay...

**Pull request closed without merging**
