### PR TITLE
Fix unknown command message with skript commands

### PR DESCRIPTION
**Pull request by Snow-Pyon**
Target Minecraft versions: any
Requirements: none
Related issues: #118, #446, #473 

Description:
Fixes the bug with Skript commands and effect commands throwing the `Unknown command. Type...` message when executed in console.

Tested it myself and worked fine.

### CODE REVIEW

**Comment by bensku** [comment]
Did you really test that this works on 1.9, 1.10, 1.11 and 1.12? Or at least check that the event in question has the method in all these versions...

**Comment by Pikachu920** [comment]
I tested this on 1.12 and can confirm that it works

**Comment by Snow-Pyon** [comment]
Tested on 1.9.0 and 1.12.2, it worked in both versions. But if you really want make sure it works on all supported versions, I don't mind setting up some serves to test it.

**Comment by bensku** [comment]
Should be good enough then. Thanks for contribution!

**Pull request merged**
