### PR TITLE
Add temperature and humidity expressions

### PR DESCRIPTION
**Pull request by Pikachu920**
Target Minecraft versions: Any
Requirements: None
Related issues: #896

Description:
Now you can get the temperature and humidity of a block

### CODE REVIEW

**Comment by Snow-Pyon** [comment]
This is already handled in LimeGlass's PR so I'm just gonna close this one

**Comment by Pikachu920** [comment]
oops, i'll just remove the seed expression and leave temp + humidity

**Comment by Snow-Pyon** [comment]
Looks good to me, thanks for the contribution!

**Comment by TheLimeGlass** [comment]
Seed expression was added already in my Pull request... https://github.com/bensku/Skript/pull/1142

**Pull request merged**
