### PR TITLE
Remove .idea folder

### PR DESCRIPTION
**Pull request by Syst3ms**
Target Minecraft versions: N/A
Requirements: N/A
Related issues: N/A

Description:
Due to .idea changes cluttering many IDEA user commits, this PR removes the .idea folder. 
The reason for all this cluttering is that the .idea folder was being tracked by Git albeit being in .gitignore, making the ignore rule not apply. Now, if an IDEA dev wants to contribute to Skript, they'll clone the repo, and IDEA will create the .idea folder itself, with it being ignored by .gitignore from the get-go, thus not showing up in commits.

If you are an IDEA developer and you want to remove .idea from your subsequent commits without having to clone Skript again, do the following command in the command line : 
```bash
git rm -r --cached .idea
```
NB : all the `deleted`/`rm` messages outputted by git only affect the index, and not your working directory.
Your own .idea folder should remain untouched by this command.

### CODE REVIEW

**Comment by xXAndrew28Xx** [comment]
👍 There's nothing special that the current .idea files in this repository do. The only thing I really configure after cloning Skript is the nullness annotations.

**Comment by Syst3ms** [comment]
If only all of them worked

**Comment by bensku** [comment]
I will wait for .gitignore PR to be merged before I merge this. No problems here, though :+1:

**Comment by bensku** [comment]
Umm. Apparently that PR was just closed. Could you add the idea files that you deleted to .gitignore @Syst3ms?

**Comment by Syst3ms** [comment]
.idea is already in gitignore, it's just that the files were still being tracked by git.

**Comment by Syst3ms** [comment]
@bensku Is there anything preventing from merge of this ?

**Comment by bensku** [comment]
Would be nice to merge your other PR before this :)

**Comment by Snow-Pyon** [comment]
Thanks for the contribution!

**Pull request merged**
