### PR TITLE
Revert "Fixed list deletion for databases"

### PR DESCRIPTION
**Pull request by RezzedUp**
Reverts bensku/Skript#791 
Fixes bensku/Skript#843

### CODE REVIEW

**Comment by bensku** [comment]
Fixed this myself, actually reverting the change was not necessary.

**Comment by Sharpjaws** [comment]
@bensku  @RezzedUp  My sincere apologies, I had no idea that my pr would break non-CSV databases as I tested this exclusively on online  SQL databases. A hotfix PR will be up asap.

**Comment by bensku** [comment]
You did not delete actual list/TreeMap from memory, which caused it to not be deleted fully from memory, even though it did disappear from DB.

**Comment by Sharpjaws** [comment]
I see, looking back at you commit that fixes this, it makes it a lot more clear that I completely forgot to clear the list from memory as I only allowed single vars to get cleared. This was very stupid. I actually can't believe that I overlooked this as all my other code was correct.

**Pull request closed without merging**
